// Generated by https://quicktype.io

export type Data = Destination[] | Crew[] | Technology[];
export type DataItem = Destination | Crew | Technology;
export type Idx = { idx: number };

export interface IData {
  destination: Destination[];
  crew: Crew[];
  technology: Technology[];
}

export interface Crew {
  name: string;
  images: Images;
  role: string;
  bio: string;
  [key: string]: any;
}

export interface Images {
  [key: string]: string;
}
// export interface Images {
//   png: string;
//   webp: string;
// }

export interface Destination {
  name: string;
  images: Images;
  description: string;
  distance: string;
  travel: string;
  [key: string]: any;
}
export interface DestinationContext {
  name: string;
  description: string;
  distance: string;
  travel: string;
}

export interface Technology {
  name: string;
  images: Images;
  description: string;
  [key: string]: any;
}

// export interface TechnologyImages {
//   [key: string]: string;
// }
// export interface TechnologyImages {
//   portrait: string;
//   landscape: string;
// }


export interface Slides {
  slides: (DataItem & Idx)[];
  numSlides: number;
}
